### ISSUE TITLE
About custom dataset

### ISSUE THREAD

**Issue by lazyDamon** [RaduAlexandru/permuto_sdf#17]
Hi, thanks for your great work. I have 2 questions about custom dataset:
1. I try to get scale and center in the following way:
     valid_poses = np.isfinite(poses).all(axis=2).all(axis=1)
    min_vertices = poses[:, :3, 3][valid_poses].min(axis=0)
    max_vertices = poses[:, :3, 3][valid_poses].max(axis=0)
    scene_scale = 1. / (np.max(max_vertices - min_vertices) + 3.)
    scene_center = (min_vertices + max_vertices) / 2.0
But the GUI shows terrible results.
2. When I set  --dataset custom, I can't extract the mesh. So I try to convert my dataset to easypbr, but results are badly. Here are some of my results, hope you can help me, thank you!
![93](https://user-images.githubusercontent.com/80307839/237022729-707bdd49-832b-4a65-b550-f46214ea122c.png)
![94](https://user-images.githubusercontent.com/80307839/237022857-79c637d2-7a25-4899-8fb5-a14bf53ae00f.png)
![mesh_res](https://user-images.githubusercontent.com/80307839/237022908-d55eac3e-89f0-45ee-9b04-bb9c4a498985.png)

**Comment by RaduAlexandru** [comment]
Hi @lazyDamon ,

It's difficult to say why the reconstruction failed in this case.
Can you please provide the dataset you are trying to use and the script you used for training and I can take a look at it?

**Comment by lazyDamon** [comment]
Hi @RaduAlexandru ,
I think I've found the problem that my camera pose has incorrect conversion. I try to use easypbr_head with colmap to do permuto_sdf, It's success! But the problem of not being able to find the correct translation and scale on custom datasets still exists. On easypbr_head with colmap, I set the translation and scale by checking whether the head displayed in the GUI is within the sphere. On custom dataset, I found that It's not useful because the center of the object seems to deviate slightly from the center of the sphere. Can you give me some advice?
![img](https://github.com/RaduAlexandru/permuto_sdf/assets/80307839/47d4b852-8097-421f-b133-8a5ebbb923fe)
![img1](https://github.com/RaduAlexandru/permuto_sdf/assets/80307839/a1dac7e5-e05e-454c-9bb2-c74df1a4ceee)
![img2](https://github.com/RaduAlexandru/permuto_sdf/assets/80307839/2bb12d0a-a61e-49f5-abc2-9991a7ebf161)
![img3](https://github.com/RaduAlexandru/permuto_sdf/assets/80307839/13ddf52a-e0cd-4376-b1b5-8299b75faf13)
![img4](https://github.com/RaduAlexandru/permuto_sdf/assets/80307839/5d86ca04-c993-49cf-bf78-a016ce1030ce)

**Comment by lazyDamon** [comment]
Here are my dataset:
[https://drive.google.com/file/d/1n6kAKRtzWzmVTgEkynyzDivkTc2jPaUX/view?usp=sharing](url)

**Comment by lazyDamon** [comment]
Here are my dataset:
[https://drive.google.com/file/d/1n6kAKRtzWzmVTgEkynyzDivkTc2jPaUX/view?usp=sharing]
Here are my training script:
`python permuto_sdf_py/experiments/run_custom_dataset/run_custom_dataset.py \
--dataset custom \
--dataset_path /permuto_sdf_data/easy_pbr_renders/mouse \
--with_mask \
--exp_info mouse`

**Comment by lazyDamon** [comment]
Here are my dataset:
[https://drive.google.com/file/d/1n6kAKRtzWzmVTgEkynyzDivkTc2jPaUX/view?usp=sharing](url)
Here are my training script:
`python permuto_sdf_py/experiments/run_custom_dataset/run_custom_dataset.py --dataset custom --dataset_path /permuto_sdf_data/easy_pbr_renders/mouse --with_mask --exp_info mouse`

**Comment by RaduAlexandru** [comment]
Hi @lazyDamon 

Thanks for providing the dataset! 

There seems to be an issue with the camera intrinsics from your data. The principal point of the camera ( the cx and cy values from your transforms.json) are way too high. I'm not sure how these values were obtained but usually cx should be close to half of the width of the image, so ~ 1920/2 and cy should be approx half the height cy=~1080/2.  I believe that due to this wrong values the training was failing. I modified them to be cx=960 and cy=540 and reran nerf2easypbr.py. This is merely just a hacky way to get values close to what they should be. Ideally the issue should be tackled by looking into whichever script created the camera calibration values.

With these modifications and tweaking a bit the scene scale and translation, I seem to get pretty good results as shown in the image. 

To reproduce these results on your end, please update the EasyPBR and PermutoSDF packages as I've made some changes to both of them. 
Afterwards you can run:
`./run_custom_dataset.py --dataset custom --with_mask --dataset_path /permuto_sdf_data/easy_pbr_renders/mouse --scene_scale 0.3 --scene_translation -0.15 0.1 0 --img_subsample 2`

Please let me know if you encounter any other issues!

![mouse3](https://github.com/RaduAlexandru/permuto_sdf/assets/11791168/c33be7ee-d5ea-4ebd-9208-ead3ae758ccd)

**Comment by lazyDamon** [comment]
Hi  @RaduAlexandru  ,
That looks very cool, I will try it. Please tell me how did you get its scene_translation and scene_scale. Thank you!

**Comment by RaduAlexandru** [comment]
In this case I got the those values with a bit of trial-and-error since I wasn't sure what the issue was that was causing the training to fail.
I started with the default of `--scene_scale 1.0 --scene_translation 0 0 0` but it was immediately clear visually that the camera frustums were not very well fitted around the sphere. So I reduced the scale and slightly adjusted the translation until the whole object started to get properly reconstructed inside the sphere. 
It's somewhat difficult to have a fully automatic method for selecting the scale so some manual tuning might still be needed. I will try to make the process easier in the future.

**Comment by lazyDamon** [comment]
Ok, I will to try, thank you!

**Comment by cduguet** [comment]
I had the camera positions but no real points (I'm using the camera position for a feature-rich calibrator object and then for the actual object), so I'm trying to obtain the positions manually. I've manually found a fitting position. Let's call them `mesh_center` and `mesh_size`. 
I tried from then calculating the scene_scale and scene_translation as: 
```
scene_scale = 1 / mesh_size
scene_translation = -mesh_center
```
But with these specific numbers, I'm running into the never-before-seen error, mid-training: 

```
phase.iter_nr 12000 loss  0.0007072705193422735
Traceback (most recent call last):
  File "./permuto_sdf_py/experiments/run_custom_dataset/run_custom_dataset.py", line 186, in <module>
    main()  # This is what you would have, but the following is useful:
  File "./permuto_sdf_py/experiments/run_custom_dataset/run_custom_dataset.py", line 181, in main
    run()
  File "./permuto_sdf_py/experiments/run_custom_dataset/run_custom_dataset.py", line 176, in run
    train(args, config_path, hyperparams, train_params, None, experiment_name, with_viewer, checkpoint_path, tensor_reel, frames_train=frames, hardcoded_cam_init=False)
  File "/data/projects/permuto_sdf/permuto_sdf_py/train_permuto_sdf.py", line 342, in train
    pred_rgb, pred_rgb_bg, pred_normals, sdf_gradients, weights_sum, fg_ray_samples_packed  =run_net(args, hyperparams, ray_origins, ray_dirs, img_indices, model_sdf, model_rgb, model_bg, model_colorcal, occupancy_grid, iter_nr_for_anneal,  cos_anneal_ratio, forced_variance)
  File "/data/projects/permuto_sdf/permuto_sdf_py/train_permuto_sdf.py", line 115, in run_net
    fg_ray_samples_packed, bg_ray_samples_packed = create_samples(args, hyperparams, ray_origins, ray_dirs, model_sdf.training, occupancy_grid, model_sdf.boundary_primitive)
  File "/data/projects/permuto_sdf/permuto_sdf_py/utils/nerf_utils.py", line 508, in create_samples
    fg_ray_samples_packed=fg_ray_samples_packed.compact_to_valid_samples()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by cduguet** [comment]
I see than in `run_custom_dataset.py`, [around this line](https://github.com/RaduAlexandru/permuto_sdf/blob/783c41fd4636b6457e2b0d63616dc82ec3b7d8d0/permuto_sdf_py/experiments/run_custom_dataset/run_custom_dataset.py#L117) that: 
* the scale is being applied first, then the translation. Shouldn't it be first the translation, then scale, at least for the way I calculated the parameters? Of course, I could scale the translation and this would still be valid, but ...
* the camera displacement is being applied in the `tf_cam_world` coordinates, while the numbers (scale, centre of the mesh) we would normally obtain from colmap are in camera to world, `tf_world_cam`. 

So my question is: 

Would this be a valid rewrite?
in `run_custom_dataset.py` lines 115-120:
```
tf_cam_world_rescaled = frame.tf_cam_world
translation=tf_cam_world_rescaled.translation().copy()
translation*=SCENE_SCALE
translation+=SCENE_TRANSLATION
tf_cam_world_rescaled.set_translation(translation)
frame.tf_cam_world=tf_cam_world_rescaled
```
and then to calculate as input: 
```
scene_scale = 1 / mesh_size
scene_translation = mesh_center * scene_scale
```
