### ISSUE TITLE
Question regarding normal calculation: why is integrating gradient necessary?

### ISSUE THREAD

**Issue by tatban** [RaduAlexandru/permuto_sdf#35]
Thanks for the cool work and sharing the well organized code. However, could you please explain the 'normal' calculation approach in the following line? I mean, usually 'normal' can be calculated either by taking the gradient of SDF network at the intersection point or even simply just by taking finite difference of SDF values in a small neighborhood around the intersection point. But what do you mean by 'integrating the gradients'? and why are you using the RGB network instead of the SDF network to calculate the 'normal'? 

https://github.com/RaduAlexandru/permuto_sdf/blob/783c41fd4636b6457e2b0d63616dc82ec3b7d8d0/permuto_sdf_py/train_permuto_sdf.py#L141

**Comment by RaduAlexandru** [comment]
Hi @tatban ,

Thank you for the interest in the work.
Indeed the normal can be computed by just taking the gradient at the intersection point. 

However, since we use the Neus formulation for the SDF, the surface intersection can be seen as "fuzzy". At the beginning of optimization, the density is very cloudy and not sharp which means the `weights` on line 141 will also be fuzzy so I integrate the gradients over the whole ray. 
This is mostly for visualization purposes since I want to visually how fuzzy the density is. 
At the end of optimization, the density is sharp and therefore `weights` look more like a unit pulse so it gives the same results as what you mention (getting the gradient of only the point along the ray the intersects the surface). 

Regarding the usage of the `model_rgb`, it is merely because the volume_integration code is a function of  this `volume_renderer_neus` which only lives inside `model_rgb`. However it doesn't use any member variables from the model_rgb so it could have also been pulled out of that object.

I hope this helps clarify the issue.

**Comment by tatban** [comment]
Thank you so much @RaduAlexandru for the nice explanation. It is clear now. So, I'm closing this issue.
